/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Petrinet2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return org.xtext.example.mydsl2.ui.internal.Petrinet2Activator.getInstance().getInjector("org.xtext.example.mydsl2.Petrinet2");
	}

}
