/**
 *
 * $Id$
 */
package petrinet2.validation;

import petrinet2.Node;

/**
 * A sample validator interface for {@link petrinet2.Arc}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArcValidator {
	boolean validate();

	boolean validateTo(Node value);
	boolean validateFrom(Node value);
}
