/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Petrinet2UiModule extends org.xtext.example.mydsl2.ui.AbstractPetrinet2UiModule {
	public Petrinet2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
