/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl2.services.Petrinet2GrammarAccess;

public class Petrinet2Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private Petrinet2GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.mydsl2.parser.antlr.internal.InternalPetrinet2Parser createParser(XtextTokenStream stream) {
		return new org.xtext.example.mydsl2.parser.antlr.internal.InternalPetrinet2Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Petrinet";
	}
	
	public Petrinet2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(Petrinet2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
