/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2.ui.contentassist

import org.xtext.example.mydsl2.ui.contentassist.AbstractPetrinet2ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Petrinet2ProposalProvider extends AbstractPetrinet2ProposalProvider {
}
