/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.mydsl2.ui.internal.Petrinet2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Petrinet2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Petrinet2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Petrinet2Activator.getInstance().getInjector(Petrinet2Activator.ORG_XTEXT_EXAMPLE_MYDSL2_PETRINET2);
	}
	
}
