/*
 * generated by Xtext
 */
package org.xtext.example.mydsl2;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Petrinet2RuntimeModule extends org.xtext.example.mydsl2.AbstractPetrinet2RuntimeModule {

}
