/*
* generated by Xtext
*/
package org.xtext.example.mydsl2;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Petrinet2StandaloneSetup extends Petrinet2StandaloneSetupGenerated{

	public static void doSetup() {
		new Petrinet2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

